# -*- coding: utf-8 -*-
"""e_Secuenciales_Tp1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CAQ4IsZdmaDxMN0t-zZfYBX9UkLzAAra

### 1) Crear un programa que imprima por pantalla el mensaje: “Hola Mundo!”.
"""

print("Hola Mundo!")

"""### 2) Crear un programa que pida al usuario su nombre e imprima por pantalla un saludo usando el nombre ingresado. Por ejemplo: si el usuario ingresa “Marcos”, el programa debe imprimir por pantalla “Hola Marcos!”. Consejo: esto será más sencillo si utilizas print(f…) para realizar la impresión por pantalla.**texto en negrita**"""

nombre = input("Ingrese su nombre: ")
print(f"Hola {nombre}!")

"""### 3) Crear un programa que pida al usuario su nombre, apellido, edad y lugar de residencia e imprima por pantalla una oración con los datos ingresados. Por ejemplo: si el usuario ingresa “Marcos”, “Pérez”, “30” y “Argentina”, el programa debe imprimir “Soy Marcos Pérez, tengo 30 años y vivo en Argentina”. Consejo: esto será más sencillo si utilizas print(f…) para realizar la impresión por pantalla.

"""

nombre = input("Ingrese su nombre: ")
apellido = input("Ingrese su apellido: ")
edad = input("Ingrese su edad: ")
lugar_residencia = input("Ingrese su lugar de residencia: ")
print(f"Soy {nombre} {apellido}, tengo {edad} años y vivo en {lugar_residencia}")

"""### 4) Crear un programa que pida al usuario el radio de un círculo e imprima por pantalla su área y su perímetro.

"""

radio = int(input("Ingrese el radio del círculo: "))
area = 3.14 * radio ** 2
perimetro = 2 * 3.14 * radio
print(f"El área del círculo es {area} y su perímetro es {perimetro}")

"""### 5) Crear un programa que pida al usuario una cantidad de segundos e imprima por pantalla a cuántas horas equivale.

"""

segundos = int(input("Ingrese una cantidad de segundos: "))
horas = segundos / 3600
print(f"La cantidad de segundos ingresada equivale a {horas} horas")

"""### 6) Crear un programa que pida al usuario un número e imprima por pantalla la tabla de multiplicar de dicho número.

"""

multiplicacdor = int(input("Ingrese un número: "))
multiplicando = 1
while multiplicando <= 10:
    print(f"{multiplicacdor} x {multiplicando} = {multiplicacdor * multiplicando}")
    multiplicando += 1

"""### 7) Crear un programa que pida al usuario dos números enteros distintos del 0 y muestre por pantalla el resultado de sumarlos, dividirlos, multiplicarlos y restarlos."""

num1 = int(input("Ingrese un número entero distinto de 0: "))
num2 = int(input("Ingrese otro número entero distinto de 0: "))
suma = num1 + num2
resta = num1 - num2
division = num1 / num2
multiplicacion = num1 * num2
print(f"suma: {suma}, resta: {resta}, multiplicacion: {multiplicacion}, division: {division}")

"""### 8) Crear un programa que pida al usuario su altura y su peso e imprima por pantalla su índice de masa corporal. Tener en cuenta que el índice de masa corporal se calcula del siguiente modo:
𝐼𝑀𝐶 = 𝑝𝑒𝑠𝑜 𝑒𝑛 𝑘𝑔 / (𝑎𝑙𝑡𝑢𝑟𝑎 𝑒𝑛 𝑚)2
"""

altura = float(input("Ingrese su altura en metros: "))
peso = float(input("Ingrese su peso en kilogramos: "))
imc = peso / (altura ** 2)
print(f"Su índice de masa corporal es {imc}")

"""### 9) Crear un programa que pida al usuario una temperatura en grados Celsius e imprima por pantalla su equivalente en grados Fahrenheit. Tener en cuenta la siguiente equivalencia:
𝑇𝑒𝑚𝑝𝑒𝑟𝑎𝑡𝑢𝑟𝑎 𝑒𝑛 𝐹𝑎ℎ𝑟𝑒𝑛ℎ𝑒𝑖𝑡 = 9/5. 𝑇𝑒𝑚𝑝𝑒𝑟𝑎𝑡𝑢𝑟𝑎 𝑒𝑛 𝐶𝑒𝑙𝑠𝑖𝑢𝑠 + 32

"""

temp = float(input("Ingrese una temperatura en grados Celsius: "))
temp_fahrenheit = (9/5) * temp + 32
print(f"La temperatura en grados Fahrenheit es {temp_fahrenheit}")

"""### 10) Crear un programa que pida al usuario 3 números e imprima por pantalla el promedio de dichos números.

"""

num1 = int(input("Ingrese un número: "))
num2 = int(input("Ingrese otro número: "))
num3 = int(input("Ingrese otro número: "))
promedio = (num1 + num2 + num3) / 3
print(f"El promedio de los números ingresados es {promedio}")